Logee-Data/logee-dwh

source/sql/dwh/bq_view/L1/visibility/lgd_category.sql

first commit for `lgd_category`

add sql file for lgd_category

---

source/sql/dwh/bq_view/L1/visibility/lgd_product.sql

Query for lgd_product

---

source/sql/dwh/bq_view/L1/visibility/lgd_sales.sql

Query for for lgd_sales

---

source/sql/dwh/bq_view/L1/visibility/lgd_service_fee_pip.sql

add sql file for lgd_service_fee_pip

Query for for lgd_service_fee_pip

---

source/sql/dwh/bq_view/L1/visibility/lgd_orders.sql

add sql file for L1 lgd_orders

---

source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql

done by Velly Ibrahim, but tackled by Amelia Kurnia Salwa

add sql file for L1 lgd_attendance

---

source/sql/dwh/bq_view/L1/visibility/lgd_sub_product.sql

done by Velly Ibrahim, but tackled by Fikri Haykal

add sql file for L1 lgd_sub_product

---

source/sql/dwh/bq_view/L1/visibility/lgd_brand.sql

table brand sudah ada di production

add sql file for L1 lgd_brand

---

dags/config/L1/visibility/lgd_service_fee_pip.yaml
dags/source/sql/dwh/L1/visibility/lgd_service_fee_pip.sql

Edit filter in sql file & add config file for airflow lgd_service_fee_pip

lgd_service_fee_pip airflow

---

dags/config/L1/visibility/dma_logee_user.yaml
dags/source/sql/dwh/L1/visibility/dma_logee_user.sql

Edit filter in sql file & add config file for airflow dma_logee_user

airflow dma_logee_user

---

dags/config/L1/visibility/dma_logee_companies.yaml
dags/source/sql/dwh/L1/visibility/dma_logee_companies.sql

Edit filter in sql file & add config file for airflow dma_logee_companies

airflow dma_logee_companies

---

dags/config/L1/visibility/lgd_sub_product.yaml
dags/source/sql/dwh/L1/visibility/lgd_sub_product.sql

submit query lgd-sub-product-airflow

---

dags/source/sql/dwh/L1/visibility/lgd_brand.sql

column synchronization between snapshot and L1

add new column in L1 lgd_brand

---

dags/source/sql/dwh/L1/visibility/lgd_voucher.sql

fix L1 lgd_voucher

---

dags/source/sql/dwh/L1/visibility/dma_logee_vehicles.sql

update l1_dma_logee_vehicles airflow

---

dags/source/sql/dwh/L1/visibility/lgd_voucher.sql

revert `voucher_id` to `data`, sorry my bad

fix lgd_voucher

---

dags/config/L2/visibility/lgd_attendance.yaml
dags/source/sql/dwh/L2/visibility/lgd_attendance.sql

submit query l2-lgd-attendance

submit query l2-lgd-attendance

---

dags/config/L2/visibility/lgd_sub_product.yaml
dags/source/sql/dwh/L1/visibility/lgd_sub_product.sql
dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql

submit query l2-lgd-sub-product

add l2-lgd-sub-product

---

dags/source/sql/dwh/L2/visibility/lgd_sales.sql

delete quality_check with comment

Fix L2 lgd_sales

---

dags/config/L2/visibility/dma_logee_vehicles.yaml
dags/source/sql/dwh/L2/visibility/dma_logee_vehicles.sql

delete quality_check with comment

fix-l2-dma-logee-vehicles
